
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    healthcheck:
      enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8095


management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/closa_recognizer?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Martona78
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
    open-in-view: true
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        connection:
          provider_disables_autocommit: true
        generate_statistics: false
        dialect: org.hibernate.dialect.MySQL55Dialect
        cache.use_second_level_cache: false
        cache.use_query_cache: false