server:
  port: 8087
logging:
  level:
    root: warn
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    healthcheck:
      enabled: true
    registerWithEureka: true
    serviceUrl:
    https://closa-eureka-service.herokuapp.com/eureka/
spring:
  datasource:
    # uri: jdbc:postgressl://isbzaldjzwoaly:da6d83176e47d0bc15aa0914694dca610147c148226d7361b1b09ef490f144ab@ec2-18-202-1-222.eu-west-1.compute.amazonaws.com:5432/d948qsjguepq4u
    url: jdbc:postgresql://ec2-18-202-1-222.eu-west-1.compute.amazonaws.com:5432/d948qsjguepq4u
    #url: jdbc:mysql://localhost:3306/closa_authentication?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: isbzaldjzwoaly
    #password: '{cipher}33308334ebb1921304d858edf2a3ec6255ab9609fd9c67821d25ede42b1fd317'
    password: da6d83176e47d0bc15aa0914694dca610147c148226d7361b1b09ef490f144ab
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
    open-in-view: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        connection:
          provider_disables_autocommit: true
        generate_statistics: false
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        cache.use_second_level_cache: false
        cache.use_query_cache: false
  management:
    endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
global:
  trace:
    local: false
    statistics: true
    audit: true
jwt:
  token:
    validity: 900000
    prefix: Bearer
  header-string: Authorization
  signing:
    key: T81SMustBeLOn9F0rF0rY0uT09etB0redt01nf1n1tWithaBSOLuteoreZ
  authorities:
    key: roles
    level: level
