
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    healthcheck:
      enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/closa_authentication?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    #password: '{cipher}33308334ebb1921304d858edf2a3ec6255ab9609fd9c67821d25ede42b1fd317'
    password: Martona78
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
    open-in-view: true
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        connection:
          provider_disables_autocommit: true
        generate_statistics: false
        dialect: org.hibernate.dialect.MySQL55Dialect
        cache.use_second_level_cache: false
        cache.use_query_cache: false
management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8686
global:
  trace:
    local: false
    statistics: true
    audit: true
encrypt:
  key: T81SMustBeLOn9F0rF0rY0uT09etB0redt01nf1n1t
jwt:
  token:
    validity: 900000
    prefix: Bearer
  header-string: Authorization
  signing-key: T81SMustBeLOn9F0rF0rY0uT09etB0redt01nf1n1tWithaBSOLuteoreZ
  authorities-key: roles
