spring:
  cloud:
    gateway:
  gateway:
    default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
    globalcors:
      add-to-simple-url-handler-mapping: true
      corsConfigurations:
        '[/**]':
          allowedOrigins:
            - "http://localhost:3000"
            - "http://localhost:3001"
          allowCredentials: true
          allowedMethods:
            - GET
            - POST
            - OPTIONS
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    healthcheck:
      enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"

server:
  port: 9090
